services:
  laravel:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel
    ports:
      - "9000:9000"

  node-dev:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_dev
    command: ["npm", "run", "dev"]
    volumes:
      - .:/var/www
    ports:
      - "5173:5173" # Vite dev server
    networks:
      - laravel

  node-build:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_build
    command: ["npm", "run", "build"]
    volumes:
      - .:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - laravel
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
