services:
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: laravel-php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  vue-dev:
    build:
      context: .
      dockerfile: docker/vue.dev.Dockerfile
    container_name: vue-dev
    volumes:
      - .:/app
    ports:
      - "5173:5173"

  vue-prod:
    build:
      context: .
      dockerfile: docker/vue.prod.Dockerfile
    container_name: vue-prod
    volumes:
      - .:/var/www/html

  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
